### ISSUE TITLE
Druid and Shaman Forms

### ISSUE THREAD

**Issue by Tamaxlia** [ForgetfulScarab/dashingDismount#1]
I don't want to presume but EZdismount had functionality to also take druids and shamans that tried to cast spells in form out of form with the first Keypress. It seems you have managed this functionality for dismount in Classic, would it be possible to add the same functionality for feral and Ghost Wolf forms or have they nerfed that somehow? Thanks very much for your consideration and taking the time to respond.

**Comment by ForgetfulScarab** [comment]
EDIT: Found that using CastShapeshiftForm(i) while in a form should take you out of it. There is a way to do it, but I will have to do some testing and might therefore take some time to implement.

Thank you for taking your time to write some feedback; much appreciated. The dismount addon is utilizing the function dismount() which uses protected Blizzard functions, and is able to do so since Blizzard wrote it. To do the same for forms like that with the limited API that we have for Classic WoW is impossible as far as I know. I'll take a look and see if I can find a workaround or a hidden gem, but I can't promise anything unfortunately. 

If you find any problems with it once you acquire your mount then please feel free to comment again.

**Comment by TWilloughby** [comment]
The macro command  /cancelform takes you out of any druid form.  Does it have an API equivalent?  I've embedded it in most of my emergency cast macros, but it would be nice to unshift when trying to talk to a vendor, access a mailbox, or drink a pot.

**Comment by ForgetfulScarab** [comment]
The equivalent would be CancelShapeshitForm() or CastShapeshiftForm(), but they both appear to be protected now that I looked again, so unsure if a solution actually exists to the problem. 

I have not been playing a lot of Classic, and I am currently focusing on other things in life, so not sure if I'll be trying to implement any other features unless it is game-breaking.

**Comment by ForgetfulScarab** [comment]
Closing this issue since both CancelShapeshiftForm() and CastShapeshiftForm() are protected. Will keep this particular feature in mind though if I manage to find any type of workaround.
